# Generated by Django 3.0.2 on 2020-01-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200125_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(max_length=10),
        ),
    ]
